language: php

env:
  - NETTE=default
  - NETTE=~2.3.0

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - php .travis.composer.php
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/tester -s -p php tests